service: express-lambda-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    - .gitignore
